storage:
  meta: ~/CDN/data
  files: /Users/asokol/CDN/data

authentication.user:
  name: popa
  password: 42

spring:
  h2:
    console.enabled: true
    console.path: /h2

  datasource:
    url: jdbc:h2:file:${storage.meta}
    username: user
    password: password
    driver-class-name: org.h2.Driver

  jpa.hibernate.ddl-auto: update